/*
 * generated by Xtext 2.10.0
 */
package com.home.knowledge.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class KnowledgeDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class OrganisationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.home.knowledge.xtext.KnowledgeDsl.Organisation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOrganisationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOrganisationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCurrentProblemKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCurrentProblemAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cCurrentProblemProblemCrossReference_4_1_0 = (CrossReference)cCurrentProblemAssignment_4_1.eContents().get(0);
		private final RuleCall cCurrentProblemProblemEStringParserRuleCall_4_1_0_1 = (RuleCall)cCurrentProblemProblemCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cExperiencesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cExperiencesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cExperiencesExperienceParserRuleCall_5_2_0 = (RuleCall)cExperiencesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cExperiencesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cExperiencesExperienceParserRuleCall_5_3_1_0 = (RuleCall)cExperiencesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Organisation:
		//	{Organisation}
		//	'Organisation'
		//	name=EString
		//	'{' ('currentProblem' currentProblem=[Problem|EString])? ('experiences' '{' experiences+=Experience (","
		//	experiences+=Experience)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Organisation} 'Organisation' name=EString '{' ('currentProblem' currentProblem=[Problem|EString])? ('experiences' '{'
		//experiences+=Experience ("," experiences+=Experience)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Organisation}
		public Action getOrganisationAction_0() { return cOrganisationAction_0; }
		
		//'Organisation'
		public Keyword getOrganisationKeyword_1() { return cOrganisationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('currentProblem' currentProblem=[Problem|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'currentProblem'
		public Keyword getCurrentProblemKeyword_4_0() { return cCurrentProblemKeyword_4_0; }
		
		//currentProblem=[Problem|EString]
		public Assignment getCurrentProblemAssignment_4_1() { return cCurrentProblemAssignment_4_1; }
		
		//[Problem|EString]
		public CrossReference getCurrentProblemProblemCrossReference_4_1_0() { return cCurrentProblemProblemCrossReference_4_1_0; }
		
		//EString
		public RuleCall getCurrentProblemProblemEStringParserRuleCall_4_1_0_1() { return cCurrentProblemProblemEStringParserRuleCall_4_1_0_1; }
		
		//('experiences' '{' experiences+=Experience ("," experiences+=Experience)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'experiences'
		public Keyword getExperiencesKeyword_5_0() { return cExperiencesKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//experiences+=Experience
		public Assignment getExperiencesAssignment_5_2() { return cExperiencesAssignment_5_2; }
		
		//Experience
		public RuleCall getExperiencesExperienceParserRuleCall_5_2_0() { return cExperiencesExperienceParserRuleCall_5_2_0; }
		
		//("," experiences+=Experience)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//experiences+=Experience
		public Assignment getExperiencesAssignment_5_3_1() { return cExperiencesAssignment_5_3_1; }
		
		//Experience
		public RuleCall getExperiencesExperienceParserRuleCall_5_3_1_0() { return cExperiencesExperienceParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.home.knowledge.xtext.KnowledgeDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ExperienceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.home.knowledge.xtext.KnowledgeDsl.Experience");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExperienceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cProblemsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cProblemsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cProblemsProblemParserRuleCall_3_2_0 = (RuleCall)cProblemsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cProblemsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cProblemsProblemParserRuleCall_3_3_1_0 = (RuleCall)cProblemsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cSolutionsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSolutionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSolutionsSolutionParserRuleCall_6_0 = (RuleCall)cSolutionsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSolutionsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSolutionsSolutionParserRuleCall_7_1_0 = (RuleCall)cSolutionsAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Experience:
		//	'Experience'
		//	name=EString
		//	'{' ('problems' '{' problems+=Problem ("," problems+=Problem)* '}')?
		//	'solutions' '{' solutions+=Solution ("," solutions+=Solution)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Experience' name=EString '{' ('problems' '{' problems+=Problem ("," problems+=Problem)* '}')? 'solutions' '{'
		//solutions+=Solution ("," solutions+=Solution)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Experience'
		public Keyword getExperienceKeyword_0() { return cExperienceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('problems' '{' problems+=Problem ("," problems+=Problem)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'problems'
		public Keyword getProblemsKeyword_3_0() { return cProblemsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//problems+=Problem
		public Assignment getProblemsAssignment_3_2() { return cProblemsAssignment_3_2; }
		
		//Problem
		public RuleCall getProblemsProblemParserRuleCall_3_2_0() { return cProblemsProblemParserRuleCall_3_2_0; }
		
		//("," problems+=Problem)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//problems+=Problem
		public Assignment getProblemsAssignment_3_3_1() { return cProblemsAssignment_3_3_1; }
		
		//Problem
		public RuleCall getProblemsProblemParserRuleCall_3_3_1_0() { return cProblemsProblemParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'solutions'
		public Keyword getSolutionsKeyword_4() { return cSolutionsKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//solutions+=Solution
		public Assignment getSolutionsAssignment_6() { return cSolutionsAssignment_6; }
		
		//Solution
		public RuleCall getSolutionsSolutionParserRuleCall_6_0() { return cSolutionsSolutionParserRuleCall_6_0; }
		
		//("," solutions+=Solution)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//solutions+=Solution
		public Assignment getSolutionsAssignment_7_1() { return cSolutionsAssignment_7_1; }
		
		//Solution
		public RuleCall getSolutionsSolutionParserRuleCall_7_1_0() { return cSolutionsSolutionParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ProblemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.home.knowledge.xtext.KnowledgeDsl.Problem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProblemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSolutionsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSolutionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSolutionsSolutionParserRuleCall_5_0 = (RuleCall)cSolutionsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSolutionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSolutionsSolutionParserRuleCall_6_1_0 = (RuleCall)cSolutionsAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Problem:
		//	'Problem'
		//	name=EString
		//	'{'
		//	'solutions' '{' solutions+=Solution ("," solutions+=Solution)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Problem' name=EString '{' 'solutions' '{' solutions+=Solution ("," solutions+=Solution)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Problem'
		public Keyword getProblemKeyword_0() { return cProblemKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'solutions'
		public Keyword getSolutionsKeyword_3() { return cSolutionsKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//solutions+=Solution
		public Assignment getSolutionsAssignment_5() { return cSolutionsAssignment_5; }
		
		//Solution
		public RuleCall getSolutionsSolutionParserRuleCall_5_0() { return cSolutionsSolutionParserRuleCall_5_0; }
		
		//("," solutions+=Solution)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//solutions+=Solution
		public Assignment getSolutionsAssignment_6_1() { return cSolutionsAssignment_6_1; }
		
		//Solution
		public RuleCall getSolutionsSolutionParserRuleCall_6_1_0() { return cSolutionsSolutionParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class SolutionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.home.knowledge.xtext.KnowledgeDsl.Solution");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSolutionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSolutionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Solution:
		//	{Solution}
		//	'Solution'
		//	name=EString
		//	'{' ('description' description=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Solution} 'Solution' name=EString '{' ('description' description=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Solution}
		public Action getSolutionAction_0() { return cSolutionAction_0; }
		
		//'Solution'
		public Keyword getSolutionKeyword_1() { return cSolutionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final OrganisationElements pOrganisation;
	private final EStringElements pEString;
	private final ExperienceElements pExperience;
	private final ProblemElements pProblem;
	private final SolutionElements pSolution;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public KnowledgeDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pOrganisation = new OrganisationElements();
		this.pEString = new EStringElements();
		this.pExperience = new ExperienceElements();
		this.pProblem = new ProblemElements();
		this.pSolution = new SolutionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.home.knowledge.xtext.KnowledgeDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Organisation:
	//	{Organisation}
	//	'Organisation'
	//	name=EString
	//	'{' ('currentProblem' currentProblem=[Problem|EString])? ('experiences' '{' experiences+=Experience (","
	//	experiences+=Experience)* '}')?
	//	'}';
	public OrganisationElements getOrganisationAccess() {
		return pOrganisation;
	}
	
	public ParserRule getOrganisationRule() {
		return getOrganisationAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Experience:
	//	'Experience'
	//	name=EString
	//	'{' ('problems' '{' problems+=Problem ("," problems+=Problem)* '}')?
	//	'solutions' '{' solutions+=Solution ("," solutions+=Solution)* '}'
	//	'}';
	public ExperienceElements getExperienceAccess() {
		return pExperience;
	}
	
	public ParserRule getExperienceRule() {
		return getExperienceAccess().getRule();
	}
	
	//Problem:
	//	'Problem'
	//	name=EString
	//	'{'
	//	'solutions' '{' solutions+=Solution ("," solutions+=Solution)* '}'
	//	'}';
	public ProblemElements getProblemAccess() {
		return pProblem;
	}
	
	public ParserRule getProblemRule() {
		return getProblemAccess().getRule();
	}
	
	//Solution:
	//	{Solution}
	//	'Solution'
	//	name=EString
	//	'{' ('description' description=EString)?
	//	'}';
	public SolutionElements getSolutionAccess() {
		return pSolution;
	}
	
	public ParserRule getSolutionRule() {
		return getSolutionAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
