/*
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext.ui.tests;

import com.google.inject.Injector;
import com.home.rh.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class RhDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("com.home.rh.xtext.RhDsl");
	}

}
