/*
 * generated by Xtext 2.10.0
 */
package com.home.knowledge.xtext.ui;

import com.google.inject.Injector;
import com.home.knowledge.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KnowledgeDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtextActivator.getInstance().getInjector(XtextActivator.COM_HOME_KNOWLEDGE_XTEXT_KNOWLEDGEDSL);
	}
	
}
