/*
 * generated by Xtext 2.10.0
 */
package com.home.knowledge.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKnowledgeDslScopeProvider extends DelegatingScopeProvider {
}
