/*
 * generated by Xtext 2.10.0
 */
package com.home.knowledge.xtext.tests

import com.google.inject.Inject
import com.home.knowledge.MOrganisation
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(KnowledgeDslInjectorProvider)
class KnowledgeDslParsingTest{

	@Inject
	ParseHelper<MOrganisation> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
