/*
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRhDslScopeProvider extends DelegatingScopeProvider {
}
