/*
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext.validation

import org.eclipse.xtext.validation.Check
import com.home.rh.xtext.rhDsl.Project
import com.home.rh.xtext.rhDsl.Employee
import org.eclipse.emf.ecore.EAttribute
import com.home.rh.xtext.rhDsl.RhDslPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RhDslValidator extends AbstractRhDslValidator {
	
	public static val INVALID_NAME = 'invalidName'
	public static val INVALID_HIGHT = 'invalidHight'
	public static val INVALID_TASKS_NUMBERS = 'invalidTasksNumbers'

	@Check
	def checkHight(Employee emp){
		val height = RhDslPackage.Literals.EMPLOYEE__HEIGHT
		
		if(emp.height<180){
			warning("The height of the employee need to be greater than 180",height , INVALID_HIGHT);
		}else if(emp.height<100){
			error("The height of the employee need to be greater than 180",height , INVALID_HIGHT);
		}
	}
	
	@Check
	def checkTaskNumbers(Project p){
		val projectTasks=RhDslPackage.Literals.PROJECT__NAME
		if((p.tasks).size<3){
			warning("Project "+p+"have less than 3 tasks !", projectTasks, INVALID_TASKS_NUMBERS);
		}
	}
	
}
