/**
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext.rhDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.home.rh.xtext.rhDsl.Project#getName <em>Name</em>}</li>
 *   <li>{@link com.home.rh.xtext.rhDsl.Project#getType <em>Type</em>}</li>
 *   <li>{@link com.home.rh.xtext.rhDsl.Project#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see com.home.rh.xtext.rhDsl.RhDslPackage#getProject()
 * @model
 * @generated
 */
public interface Project extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.home.rh.xtext.rhDsl.RhDslPackage#getProject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.home.rh.xtext.rhDsl.Project#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see com.home.rh.xtext.rhDsl.RhDslPackage#getProject_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link com.home.rh.xtext.rhDsl.Project#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link com.home.rh.xtext.rhDsl.Task}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tasks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see com.home.rh.xtext.rhDsl.RhDslPackage#getProject_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

} // Project
