/*
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RhDslStandaloneSetup extends RhDslStandaloneSetupGenerated {

	def static void doSetup() {
		new RhDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
