/*
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRhDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.home.rh.xtext.rhDsl.RhDslPackage.eINSTANCE);
		return result;
	}
	
}
