/*
 * generated by Xtext 2.10.0
 */
package com.home.knowledge.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KnowledgeDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/home/knowledge/xtext/parser/antlr/internal/InternalKnowledgeDsl.tokens");
	}
}
