/*
 * generated by Xtext 2.10.0
 */
package com.home.knowledge.xtext.parser.antlr;

import com.google.inject.Inject;
import com.home.knowledge.xtext.parser.antlr.internal.InternalKnowledgeDslParser;
import com.home.knowledge.xtext.services.KnowledgeDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KnowledgeDslParser extends AbstractAntlrParser {

	@Inject
	private KnowledgeDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKnowledgeDslParser createParser(XtextTokenStream stream) {
		return new InternalKnowledgeDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Organisation";
	}

	public KnowledgeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KnowledgeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
