/*
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import com.home.rh.xtext.ide.contentassist.antlr.internal.InternalRhDslParser;
import com.home.rh.xtext.services.RhDslGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class RhDslParser extends AbstractContentAssistParser {

	@Inject
	private RhDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalRhDslParser createParser() {
		InternalRhDslParser result = new InternalRhDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDurationTypeAccess().getAlternatives(), "rule__DurationType__Alternatives");
					put(grammarAccess.getCompanyAccess().getGroup(), "rule__Company__Group__0");
					put(grammarAccess.getCompanyAccess().getGroup_4(), "rule__Company__Group_4__0");
					put(grammarAccess.getEmployeeAccess().getGroup(), "rule__Employee__Group__0");
					put(grammarAccess.getEmployeeAccess().getGroup_2(), "rule__Employee__Group_2__0");
					put(grammarAccess.getEmployeeAccess().getGroup_3(), "rule__Employee__Group_3__0");
					put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
					put(grammarAccess.getProjectAccess().getGroup_2(), "rule__Project__Group_2__0");
					put(grammarAccess.getTaskAccess().getGroup(), "rule__Task__Group__0");
					put(grammarAccess.getTaskAccess().getGroup_11(), "rule__Task__Group_11__0");
					put(grammarAccess.getCompanyAccess().getNameAssignment_2(), "rule__Company__NameAssignment_2");
					put(grammarAccess.getCompanyAccess().getEmployeesAssignment_4_2(), "rule__Company__EmployeesAssignment_4_2");
					put(grammarAccess.getCompanyAccess().getProjectsAssignment_5(), "rule__Company__ProjectsAssignment_5");
					put(grammarAccess.getEmployeeAccess().getNameAssignment_1(), "rule__Employee__NameAssignment_1");
					put(grammarAccess.getEmployeeAccess().getWeightAssignment_2_1(), "rule__Employee__WeightAssignment_2_1");
					put(grammarAccess.getEmployeeAccess().getHeightAssignment_3_1(), "rule__Employee__HeightAssignment_3_1");
					put(grammarAccess.getProjectAccess().getNameAssignment_1(), "rule__Project__NameAssignment_1");
					put(grammarAccess.getProjectAccess().getTypeAssignment_2_1(), "rule__Project__TypeAssignment_2_1");
					put(grammarAccess.getProjectAccess().getTasksAssignment_4(), "rule__Project__TasksAssignment_4");
					put(grammarAccess.getTaskAccess().getNameAssignment_1(), "rule__Task__NameAssignment_1");
					put(grammarAccess.getTaskAccess().getResponsableAssignment_3(), "rule__Task__ResponsableAssignment_3");
					put(grammarAccess.getTaskAccess().getDescriptionAssignment_5(), "rule__Task__DescriptionAssignment_5");
					put(grammarAccess.getTaskAccess().getStartDateAssignment_7(), "rule__Task__StartDateAssignment_7");
					put(grammarAccess.getTaskAccess().getDurationAssignment_9(), "rule__Task__DurationAssignment_9");
					put(grammarAccess.getTaskAccess().getDurationTypeAssignment_10(), "rule__Task__DurationTypeAssignment_10");
					put(grammarAccess.getTaskAccess().getSubtasksAssignment_11_2(), "rule__Task__SubtasksAssignment_11_2");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalRhDslParser typedParser = (InternalRhDslParser) parser;
			typedParser.entryRuleCompany();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RhDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RhDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
