/*
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RhDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/home/rh/xtext/parser/antlr/internal/InternalRhDsl.tokens");
	}
}
