/*
 * generated by Xtext 2.10.0
 */
package com.home.rh.xtext.parser.antlr;

import com.google.inject.Inject;
import com.home.rh.xtext.parser.antlr.internal.InternalRhDslParser;
import com.home.rh.xtext.services.RhDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RhDslParser extends AbstractAntlrParser {

	@Inject
	private RhDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRhDslParser createParser(XtextTokenStream stream) {
		return new InternalRhDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Company";
	}

	public RhDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RhDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
